/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IIc:outlineRemoveCircle': typeof import('~icons/ic/outline-remove-circle')['default']
    'IMaterialSymbols:addCircleRounded': typeof import('~icons/material-symbols/add-circle-rounded')['default']
    'IMaterialSymbols:dataInfoAlertRounded': typeof import('~icons/material-symbols/data-info-alert-rounded')['default']
    'IMaterialSymbols:delete': typeof import('~icons/material-symbols/delete')['default']
    'IMaterialSymbols:editSquareRounded': typeof import('~icons/material-symbols/edit-square-rounded')['default']
    'IMaterialSymbols:nightsStayRounded': typeof import('~icons/material-symbols/nights-stay-rounded')['default']
    'IMaterialSymbols:wbSunnyRounded': typeof import('~icons/material-symbols/wb-sunny-rounded')['default']
  }
}
